/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedCareersRouteImport } from './routes/_authenticated/careers'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated/chatbot'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInternshipsRouteImport } from './routes/_authenticated/internships'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareersRoute = AuthenticatedCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternshipsRoute =
  AuthenticatedInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/careers': typeof AuthenticatedCareersRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/internships': typeof AuthenticatedInternshipsRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assessment'
    | '/careers'
    | '/chatbot'
    | '/courses'
    | '/dashboard'
    | '/internships'
    | '/interview'
    | '/profile'
    | '/progress'
    | '/resume'
    | '/roadmap'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assessment'
    | '/careers'
    | '/chatbot'
    | '/courses'
    | '/dashboard'
    | '/internships'
    | '/interview'
    | '/profile'
    | '/progress'
    | '/resume'
    | '/roadmap'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assessment'
    | '/_authenticated/careers'
    | '/_authenticated/chatbot'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/internships'
    | '/_authenticated/interview'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/resume'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers': {
      id: '/_authenticated/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AuthenticatedCareersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internships': {
      id: '/_authenticated/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof AuthenticatedInternshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedCareersRoute: typeof AuthenticatedCareersRoute
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInternshipsRoute: typeof AuthenticatedInternshipsRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedCareersRoute: AuthenticatedCareersRoute,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInternshipsRoute: AuthenticatedInternshipsRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
